import {
  linkedin,
  alastairdouglas,
  christinehuynh,
  glenshiell,
  josephtuma,
  paulasylvia,
  sambowman,
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage2,
  chromecast,
  disc02,
  discord,
  facebook,
  figma,
  file02,
  framer,
  homeSmile,
  instagram,
  notification2,
  notification3,
  notification4,
  notion,
  photoshop,
  plusSquare,
  protopie,
  raindrop,
  recording01,
  recording03,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  searchMd,
  slack,
  sliders04,
  telegram,
  twitter,
  puresalmon,
  barramundiasia,
  ssc,
  vda,
  ssf,
  heats,
  bom,
  tassal,
  huon,
  marineharvest,
  cleanseas,
  skretting,
  youngs,
  santos,
  pandp,
  mbc,
  cbb,
  sunwell,
  pep,
  nzking,
  tsfc,
  eawp,
  archer,
  aquatec,
  aquatiq,
  calkins,
  eachmile,
  mtcook,
  naqua,
  nutreco,
  openbluecobia,
  pacific,
  paspaley,
  solvay,
  veramaris,
  benefitCard1,
  benefitCard2,
  benefitCard3,
  benefitCard4,
  benefitCard5,
  benefitCard6,
  checkingSalmon,
} from "../assets";

export const navigation = [
  {
    id: "0",
    title: "Services",
    url: "#services",
  },
  {
    id: "1",
    title: "About",
    url: "#about",
  },
  {
    id: "2",
    title: "Team",
    url: "#team",
  },
  {
    id: "3",
    title: "Products",
    url: "#products",
  },
  {
    id: "4",
    title: "New account",
    url: "#signup",
    onlyMobile: true,
  },
  {
    id: "5",
    title: "Sign in",
    url: "#login",
    onlyMobile: true,
  },
];

export const heroIcons = [homeSmile, file02, searchMd, plusSquare];

export const notificationImages = [notification4, notification3, notification2];

export const companyLogos = [
  puresalmon,
  barramundiasia,
  ssc,
  vda,
  ssf,
  heats,
  bom,
  tassal,
  huon,
  marineharvest,
  cleanseas,
  skretting,
  youngs,
  santos,
  pandp,
  mbc,
  cbb,
  sunwell,
  pep,
  nzking,
  tsfc,
  eawp,
  archer,
  aquatec,
  aquatiq,
  calkins,
  eachmile,
  mtcook,
  naqua,
  nutreco,
  openbluecobia,
  pacific,
  paspaley,
  solvay,
  veramaris,
];

export const brainwaveServices = [
  "Fast, uniform cooling",
  "Improve operation efficiency",
  "Higher filleting yield",
  "Extended shelf life",
];

export const brainwaveServicesIcons = [
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
];

export const roadmap = [
  {
    id: "0",
    title: "Voice recognition",
    text: "Enable the chatbot to understand and respond to voice commands, making it easier for users to interact with the app hands-free.",
    date: "May 2023",
    status: "done",
    imageUrl: roadmap1,
    colorful: true,
  },
  {
    id: "1",
    title: "Gamification",
    text: "Add game-like elements, such as badges or leaderboards, to incentivize users to engage with the chatbot more frequently.",
    date: "May 2023",
    status: "progress",
    imageUrl: roadmap2,
  },
  {
    id: "2",
    title: "Chatbot customization",
    text: "Allow users to customize the chatbot's appearance and behavior, making it more engaging and fun to interact with.",
    date: "May 2023",
    status: "done",
    imageUrl: roadmap3,
  },
  {
    id: "3",
    title: "Integration with APIs",
    text: "Allow the chatbot to access external data sources, such as weather APIs or news APIs, to provide more relevant recommendations.",
    date: "May 2023",
    status: "progress",
    imageUrl: roadmap4,
  },
];

export const collabText =
  "SmartAqua was first established in 1996 by Alastair Smart to offer seafood consulting services chiefly to the fast growing aquaculture industry. After some years working in many countries he saw a number of colleagues offering the same service and the concept of a Team offering a one-stop-shop for seafood advice not limited by scope or geography was formed and the group expanded globally.";

export const collabContent = [
  {
    id: "0",
    title: "Total Site Project Management",
    text: "Aquaculture Development Project Management, Veterinary Services, Biosecurity and Health Management ",
  },
  {
    id: "1",
    title: "Landbased Aquaculture (RAS) Facilities",
    text: "Design, Construct and Management",
  },
  {
    id: "2",
    title: "Production Planning",
    text: "External Auditing & Site Assessment Services, Sustainable Seafood Sourcing",
  },
  {
    id: "3",
    title: "Process Plant Design",
    text: "Seafood Processing Plant Design, Seafood Supply Chain DLT Traceability Solutions",
  },
  {
    id: "4",
    title: "Construction",
    text: "Seafood Business Realty Facilitation, Skilled Talent Sourcing, Training Seminars",
  },
  {
    id: "5",
    title: "Mergers and Acquisitions",
    text: "Due Diligence for PE firms, VC's, Incubators and Accelerators, Board Risk Advisory and Governance Services",
  },
];

export const collabApps = [
  {
    id: "0",
    title: "Figma",
    icon: figma,
    width: 26,
    height: 36,
  },
  {
    id: "1",
    title: "Notion",
    icon: notion,
    width: 34,
    height: 36,
  },
  {
    id: "2",
    title: "Discord",
    icon: discord,
    width: 36,
    height: 28,
  },
  {
    id: "3",
    title: "Slack",
    icon: slack,
    width: 34,
    height: 35,
  },
  {
    id: "4",
    title: "Photoshop",
    icon: photoshop,
    width: 34,
    height: 34,
  },
  {
    id: "5",
    title: "Protopie",
    icon: protopie,
    width: 34,
    height: 34,
  },
  {
    id: "6",
    title: "Framer",
    icon: framer,
    width: 26,
    height: 34,
  },
  {
    id: "7",
    title: "Raindrop",
    icon: raindrop,
    width: 38,
    height: 32,
  },
];

export const pricing = [
  {
    id: "0",
    title: "Basic",
    description: "AI chatbot, personalized recommendations",
    price: "0",
    features: [
      "An AI chatbot that can understand your queries",
      "Personalized recommendations based on your preferences",
      "Ability to explore the app and its features without any cost",
    ],
  },
  {
    id: "1",
    title: "Premium",
    description: "Advanced AI chatbot, priority support, analytics dashboard",
    price: "9.99",
    features: [
      "An advanced AI chatbot that can understand complex queries",
      "An analytics dashboard to track your conversations",
      "Priority support to solve issues quickly",
    ],
  },
  {
    id: "2",
    title: "Enterprise",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    features: [
      "An AI chatbot that can understand your queries",
      "Personalized recommendations based on your preferences",
      "Ability to explore the app and its features without any cost",
    ],
  },
];

export const team = [
  // {
  //   id: "0",
  //   name: "Alastair Smart",
  //   text: "xxx",
  //   imageUrl: benefitImage2,

  // },
  {
    id: "1",
    name: "Alastair Douglas",
    imageUrl: alastairdouglas,
    lnlink: "https://www.linkedin.com/in/alistair-douglas-a5b99a38/",
  },
  {
    id: "2",
    name: "Christine Huynh",
    imageUrl: christinehuynh,
    lnlink: "https://www.linkedin.com/in/christine-huynh-2282aa53/",
  },
  {
    id: "3",
    name: "Glen Shiell",
    imageUrl: glenshiell,
    lnlink: "https://www.linkedin.com/in/gshiell/",
  },
  {
    id: "4",
    name: "Joseph Tuma",
    imageUrl: josephtuma,
    lnlink: "https://www.linkedin.com/in/joseph-tuma-3b56451a/",
  },
  {
    id: "5",
    name: "Paula Sylvia",
    imageUrl: paulasylvia,
    lnlink: "https://www.linkedin.com/in/paula-sylvia-91002364/",
  },
  {
    id: "6",
    name: "Sam Bowman",
    imageUrl: sambowman,
    lnlink: "https://www.linkedin.com/in/sam-bowman-marketing27/",
  },
];

export const benefits = [
  {
    id: "0",
    title: "xxx",
    text: "xxx",
    backgroundUrl: benefitCard1,
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
    light: true,
    url: "#hero",
  },
  {
    id: "1",
    title: "xxxTotal Site Project Managementxxx",
    text: "xxxAquaculture Development Project Management, Veterinary Services, Biosecurity and Health Managementxxx ",
    backgroundUrl: benefitCard2,
    iconUrl: benefitIcon2,
    imageUrl: checkingSalmon,
    light: true,
  },
  {
    id: "2",
    title: "xxxx",
    text: "xxxx",
    backgroundUrl: benefitCard3,
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
  },
  {
    id: "3",
    title: "xxxx",
    text: "xxxxx",
    backgroundUrl: benefitCard4,
    iconUrl: benefitIcon4,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "4",
    title: "xxx",
    text: "xxx",
    backgroundUrl: benefitCard5,
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "5",
    title: "xxxxxx",
    text: "xxxxx",
    backgroundUrl: benefitCard6,
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
  },
];

export const socials = [
  {
    id: "0",
    title: "Linked In",
    iconUrl: linkedin,
    url: "https://www.linkedin.com/company/smartaqua/",
  },
  {
    id: "1",
    title: "Twitter",
    iconUrl: twitter,
    url: "#",
  },
  {
    id: "2",
    title: "Contact",
    url: "#",
  },
  // {
  //   id: "3",
  //   title: "Telegram",
  //   iconUrl: telegram,
  //   url: "#",
  // },
  // {
  //   id: "4",
  //   title: "Facebook",
  //   iconUrl: facebook,
  //   url: "#",
  // },
];
